content:
  - name: categories
    label: Categories
    path: apps/web/lib/categories.ts
    type: file
  - name: posts
    label: Posts
    path: apps/web/content/blo
    type: collection
    filename: field.title.mdx
    view:
      fields: [ title ]