content:
  - name: categories
    label: Categories
    path: apps/web/lib/categories.ts
    type: file
  - name: blog
    label: Blog
    path: apps/web/content/blog
    type: collection
    filename: field.title.mdx
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
        options:
         rows: 2
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd
      - name: body
        label: Body
        type: text