content:
  - name: categories
    label: Categories
    path: apps/web/lib/categories.ts
    type: file
  - name: posts
    label: Posts
    path: apps/web/content/blog
    type: collection
    filename: field.title.mdx
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: date
        label: Date
        type: date
        format: yyyy-MM-dd
      - name: body
        label: Body
        type: text